// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfjzsreawhhlzyqcyyus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmanpzcmVhd2hobHp5cWN5eXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzIxMzAsImV4cCI6MjA3MTE0ODEzMH0.ycA7NiQbD77tlK81J0zzWZ6v7kF2H-1Nt3Y_ScqHbbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});